name: movies_search
description: Search movies using API OMDb with Clean Architecture by Flutterando

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  rxdart: ^0.24.1
  flutter_modular: ^2.0.1
  cached_network_image: ^2.2.0+1
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  mobx_codegen: ^1.0.3
  build_runner: ^1.9.0
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/semposter.png